Repository Gila-part4/Gila, pull requests merged in 2024-08, with the labels that each got.

#41 액티비티 생성 폼 작업
  app/(protected)/(user)/dashboard/my-activity/_components/activity-create-form.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/detail-info-section.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/location-select-section.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/schedule-section.tsx
  components/ui/accordion.tsx
  components/ui/calendar.tsx
  components/ui/textarea.tsx
  constants/tag.ts
  package-lock.json
  package.json
  tailwind.config.ts
Labels: feature, style

#51 토픽 페이지 api 연동
  app/(protected)/topic/_components/tag-footer.tsx
  app/(protected)/topic/page.tsx
  app/action/user.ts
  middleware.ts
Labels: feature

#58 uploadthing 등록 작업 완료
  app/api/uploadthing/core.ts
  app/api/uploadthing/route.ts
  components/file-upload.tsx
  lib/uploadthing.ts
  middleware.ts
  next.config.mjs
  package.json
  routes.ts
Labels: feature

#59 Dev fix
  tailwind.config.ts
Labels: bug, fix

#49 대시보드 내비게이션 바 구현
  app/(protected)/(user)/(dashboard)/_components/dashboard-nav.tsx
  app/(protected)/(user)/(dashboard)/_components/nav-icon-link.tsx
  app/(protected)/(user)/(dashboard)/_components/plus-button.tsx
  app/(protected)/(user)/(dashboard)/layout.tsx
  app/(protected)/(user)/(dashboard)/my-activity/_components/my-activity-card.tsx
  app/(protected)/(user)/(dashboard)/my-activity/page.tsx
  app/(protected)/(user)/(dashboard)/my-question/_components/my-question-card.tsx
  app/(protected)/(user)/(dashboard)/my-question/page.tsx
  app/(protected)/(user)/(dashboard)/promise-list/_components/promise-list-card.tsx
  app/(protected)/(user)/(dashboard)/promise-list/_components/promise-status.tsx
  app/(protected)/(user)/(dashboard)/promise-list/page.tsx
  app/(protected)/(user)/(dashboard)/promised-list/_components/promised-list-card.tsx
  app/(protected)/(user)/(dashboard)/promised-list/page.tsx
  app/(protected)/(user)/(dashboard)/reviews/_components/rating-selector.tsx
  app/(protected)/(user)/(dashboard)/reviews/_components/reviews-card.tsx
  app/(protected)/(user)/(dashboard)/reviews/page.tsx
  app/(protected)/(user)/(dashboard)/wishlist/_components/wishlist-card.tsx
  app/(protected)/(user)/(dashboard)/wishlist/page.tsx
  app/(protected)/(user)/dashboard/layout.tsx
Labels: feature, style

#45 프로필 페이지
  app/(protected)/(user)/profile/_components/profile-image.tsx
  app/(protected)/(user)/profile/_components/profile-nav-route.tsx
  app/(protected)/(user)/profile/_components/profile-topic.tsx
  app/(protected)/(user)/profile/edit/_components/edit-image-form.tsx
  app/(protected)/(user)/profile/edit/_components/edit-item-nickname.tsx
  app/(protected)/(user)/profile/edit/_components/edit-item-password.tsx
  app/(protected)/(user)/profile/edit/_components/edit-nickname-form.tsx
  app/(protected)/(user)/profile/edit/_components/edit-password-form.tsx
  app/(protected)/(user)/profile/edit/_components/edit-profile-item.tsx
  app/(protected)/(user)/profile/edit/_components/edit-profile-topic.tsx
  app/(protected)/(user)/profile/edit/_components/render-avatar.tsx
  app/(protected)/(user)/profile/edit/page.tsx
  app/(protected)/(user)/profile/layout.tsx
  app/(protected)/(user)/profile/page.tsx
  app/(protected)/[activityId]/_components/detail-title.tsx
  app/(protected)/topic/_components/tag-carousel.tsx
  app/(protected)/topic/_components/tag-footer.tsx
  app/(protected)/topic/page.tsx
  app/(public)/introduction/[introductionId]/_components/profile-rank.tsx
  app/(public)/introduction/[introductionId]/page.tsx
  app/(public)/introduction/page.tsx
  app/action/user.ts
  components/profile-item.tsx
  public/default-profile-image.png
Labels: feature

#62 상세 페이지 구현
  KakaoScript.tsx
  app/(protected)/(main)/question-list/_components/answer-button-container.tsx
  app/(protected)/(main)/question-list/_components/answer-list.tsx
  app/(protected)/(main)/question-list/_components/question-detail-modal.tsx
  app/(protected)/(main)/question-list/_components/question-list-card.tsx
  app/(protected)/(main)/question-list/_components/question-list.tsx
  app/(protected)/[activityId]/_components/author-info.tsx
  app/(protected)/[activityId]/_components/detail-carousel.tsx
  app/(protected)/[activityId]/_components/detail-content.tsx
  app/(protected)/[activityId]/_components/detail-description.tsx
  app/(protected)/[activityId]/_components/detail-title.tsx
  app/(protected)/[activityId]/_components/promise-request-form.tsx
  app/(protected)/[activityId]/_components/share-popover.tsx
  app/(protected)/[activityId]/page.tsx
  app/(protected)/topic/_components/tag-footer.tsx
  app/(protected)/topic/page.tsx
  app/action/activity.ts
  app/action/favorite.ts
  app/data/answer.ts
  app/layout.tsx
  components/delete-alert-modal.tsx
  next.config.mjs
Labels: feature

#63 메인 페이지 활동 리스트와 드롭다운 구현
  app/(protected)/(main)/_components/carousel-card.tsx
  app/(protected)/(main)/_components/carousel-text.tsx
  app/(protected)/(main)/_components/main-carousel.tsx
  app/(protected)/(main)/_components/nav-with-combobox.tsx
  app/(protected)/(main)/_components/nav-with-route.tsx
  app/(protected)/(main)/_components/profile-dropdown.tsx
  app/(protected)/(main)/activity-list/_components/activity-container.tsx
  app/(protected)/(main)/activity-list/_components/activity-list-card.tsx
  app/(protected)/(main)/activity-list/_components/activity-list.tsx
  app/(protected)/(main)/activity-list/_components/sorting-dropdown.tsx
  app/(protected)/(main)/activity-list/page.tsx
  app/(protected)/(main)/question-list/_components/question-list-card.tsx
  app/(protected)/(main)/question-list/_components/question-list.tsx
  app/data/activity.ts
  constants/sort.ts
  next.config.mjs
Labels: feature, style

#69 답변 이미지 삽입 기능
  app/(protected)/(main)/question-list/_components/answer-form.tsx
  app/(protected)/(main)/question-list/_components/answer-item.tsx
  components/upload-button.tsx
Labels: feature

#77 리뷰 페이지 데이터 패칭 작업 완료.
  app/(protected)/(user)/(dashboard)/reviews/_components/review-list.tsx
  app/(protected)/(user)/(dashboard)/reviews/_components/reviews-card.tsx
  app/(protected)/(user)/(dashboard)/reviews/page.tsx
  app/action/review.ts
  app/data/activity.ts
Labels: feature

#78 약속 요청 페이지 구현
  app/(protected)/(user)/(dashboard)/promise-list/_components/promise-list-card.tsx
  app/(protected)/(user)/(dashboard)/promise-list/_components/promise-list.tsx
  app/(protected)/(user)/(dashboard)/promise-list/page.tsx
  app/(protected)/[activityId]/_components/author-info.tsx
  app/action/activity-request.ts
  components/image-card.tsx
Labels: feature

#80 프로필페이지 수정
  app/(protected)/(user)/profile/edit/_components/edit-image-form.tsx
  app/(protected)/(user)/profile/edit/_components/edit-item-password.tsx
  app/(protected)/(user)/profile/edit/_components/edit-password-form.tsx
  app/(protected)/(user)/profile/edit/_components/edit-profile-item.tsx
  app/(protected)/(user)/profile/edit/_components/edit-profile-topic.tsx
  app/(protected)/(user)/profile/edit/_components/render-avatar.tsx
  app/(protected)/(user)/profile/edit/page.tsx
Labels: style, refactor

#82 my-question 페이지 구현
  app/(protected)/(user)/(dashboard)/my-question/_components/my-question-card.tsx
  app/(protected)/(user)/(dashboard)/my-question/_components/my-question-create-modal.tsx
  app/(protected)/(user)/(dashboard)/my-question/_components/my-question-edit-form.tsx
  app/(protected)/(user)/(dashboard)/my-question/_components/my-question-form.tsx
  app/(protected)/(user)/(dashboard)/my-question/_components/my-question-kebab.tsx
  app/(protected)/(user)/(dashboard)/my-question/_components/my-question-list.tsx
  app/(protected)/(user)/(dashboard)/my-question/page.tsx
  app/action/question.ts
  components/ui/dialog.tsx
Labels: feature

#85 (my-question) 댓글 있을 때 수정 막기
  app/(protected)/(user)/(dashboard)/my-question/_components/my-question-card.tsx
  app/(protected)/(user)/(dashboard)/my-question/_components/my-question-kebab.tsx
Labels: refactor

#87 위시리스트 작성자 삭제
  app/(protected)/(user)/(dashboard)/wishlist/_components/wishlist-card.tsx
  app/(protected)/(user)/(dashboard)/wishlist/_components/wishlist-container.tsx
  app/(protected)/(user)/(dashboard)/wishlist/_components/wishlist-heart-icon.tsx
  app/(protected)/(user)/(dashboard)/wishlist/_components/wishlist-heart-loading.tsx
  app/(protected)/(user)/(dashboard)/wishlist/_components/wishlist-image-card.tsx
Labels: fix

#86 답변 이미지 수정
  app/(protected)/(main)/activity-list/_components/activity-list-card.tsx
  app/(protected)/(main)/question-list/_components/answer-button-container.tsx
  app/(protected)/(main)/question-list/_components/answer-edit-form.tsx
  app/(protected)/(main)/question-list/_components/answer-form.tsx
  app/(protected)/(main)/question-list/_components/answer-item.tsx
  app/(protected)/(user)/(dashboard)/my-activity/_components/my-activity-card.tsx
  app/(protected)/(user)/(dashboard)/promise-list/_components/promise-list-card.tsx
  app/(protected)/(user)/(dashboard)/reviews/_components/review-list.tsx
  app/(protected)/(user)/(dashboard)/reviews/_components/reviews-card.tsx
  app/(protected)/(user)/(dashboard)/wishlist/_components/wishlist-image-card.tsx
  app/(protected)/[activityId]/_components/promise-request-form.tsx
  components/delete-alert-modal.tsx
  utils/formatDateRange.tsx
Labels: refactor

#91 머지후 에러 긴급 수정
  app/(protected)/(user)/dashboard/my-question/_components/my-question-kebab.tsx
  app/(protected)/(user)/dashboard/wishlist/_components/wishlist-container.tsx
  app/(protected)/(user)/dashboard/wishlist/_components/wishlist-heart-icon.tsx
Labels: bug, fix

#90 작성자 소개 페이지 뒤로가기 버튼
  app/(protected)/(user)/dashboard/wishlist/_components/wishlist-card.tsx
  app/(public)/introduction/[introductionId]/_components/back-button.tsx
  app/(public)/introduction/[introductionId]/page.tsx
Labels: feature

#92 질문 페이지 지역 sort 추가
  app/(protected)/(main)/activity-list/_components/activity-list.tsx
  app/(protected)/(main)/question-list/_components/answer-item.tsx
  app/(protected)/(main)/question-list/_components/question-detail-modal.tsx
  app/(protected)/(main)/question-list/_components/question-sort-dropdown.tsx
  app/(protected)/(main)/question-list/page.tsx
  app/(protected)/(user)/dashboard/wishlist/_components/wishlist-image-card.tsx
Labels: fix, refactor

#93 이미지 배열 업로드 구현
  app/(protected)/(user)/dashboard/my-activity/_components/activity-create-form.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/activity-create-modal.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/detail-info-section.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/my-activity-card.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/my-activity-list.tsx
  app/action/activity.ts
  app/api/uploadthing/core.ts
  app/api/uploadthing/route.ts
  app/data/activity.ts
  components/file-upload.tsx
  components/image-card.tsx
  components/multi-file-upload.tsx
  components/upload-button.tsx
  lib/uploadthing.ts
Labels: feature

#94 상세페이지 즐겨찾기, 조회수 브라우저 즉시 적용
  app/(protected)/[activityId]/_components/detail-title.tsx
Labels: fix

#95 신청현황 마크업 및 로직 수정
  app/(protected)/(user)/dashboard/promised-list/_components/promised-list-card.tsx
  app/(protected)/(user)/dashboard/promised-list/_components/promised-list.tsx
  app/data/activity-request.ts
  components/user-icon.tsx
  type.ts
Labels: feature

#96 이미지 업로드 버튼 수정
  app/(protected)/(main)/question-list/_components/answer-edit-form.tsx
  app/(protected)/(main)/question-list/_components/answer-form.tsx
  app/(protected)/(user)/profile/edit/_components/edit-image-form.tsx
Labels: fix

#98 커서아이디 초기화 삭제
  app/(protected)/(user)/dashboard/promised-list/_components/promised-list.tsx
Labels: bug, fix

#99 최신순 정렬 초기값 적용되도록 수정
  app/(protected)/(main)/activity-list/_components/sorting-dropdown.tsx
Labels: fix

#102 이미지카드 src안들어간거 수정
  app/(protected)/(user)/dashboard/promise-list/_components/promise-list-card.tsx
  app/(protected)/(user)/dashboard/promised-list/_components/promised-list-card.tsx
Labels: bug, fix

#109 본인 활동 본인 신청 방지 및 카카오톡 메세지 설정
  app/(protected)/[activityId]/_components/detail-content.tsx
  app/(protected)/[activityId]/_components/detail-title.tsx
  app/(protected)/[activityId]/_components/share-popover.tsx
  app/action/activity-request.ts
  app/favicon.ico
Labels: fix, refactor

#110 이미지 생성 폼 수정
  app/(protected)/(user)/dashboard/my-activity/_components/activity-create-form.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/detail-info-section.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/location-select-section.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/schedule-section.tsx
  components/location-select-drawer.tsx
  components/ui/drawer.tsx
  components/ui/form.tsx
  package.json
  tailwind.config.ts
Labels: feature, fix

#111 랜딩페이지와 인증페이지 스타일 마크업 수정
  app/(auth)/layout.tsx
  app/(auth)/sign-in/_components/login-form.tsx
  app/(auth)/sign-in/page.tsx
  app/(auth)/sign-up/_components/register-form.tsx
  app/(auth)/sign-up/page.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/activity-create-form.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/detail-info-section.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/location-select-section.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/schedule-section.tsx
  app/(protected)/[activityId]/_components/detail-content.tsx
  app/(protected)/[activityId]/_components/detail-title.tsx
  app/(protected)/[activityId]/_components/share-popover.tsx
  app/(protected)/_components/nav-dropdown.tsx
  app/(public)/_components/landing-hero-section.tsx
  app/(public)/_components/landing-main-section.tsx
  app/(public)/_components/landing-nav.tsx
  app/(public)/introduction/[introductionId]/page.tsx
  app/(public)/introduction/rank-test/page.tsx
  app/(public)/page.tsx
  app/action/activity-request.ts
  app/action/user.ts
  app/favicon.ico
  app/layout.tsx
  components/common/back-button.tsx
  components/location-select-drawer.tsx
  components/ui/drawer.tsx
  components/ui/form.tsx
  components/ui/password-input.tsx
  components/ui/sonner.tsx
  package.json
  schema.ts
  tailwind.config.ts
Labels: style

#112 정렬 상태와 이미지 업로드 스타일 적용
  app/(protected)/(main)/activity-list/_components/sorting-dropdown.tsx
  app/(protected)/(user)/dashboard/promised-list/_components/promised-list-card.tsx
  app/(public)/introduction/[introductionId]/_components/back-button 2.tsx
  app/(public)/introduction/rank-test/page 2.tsx
  app/action/activity-request.ts
  app/data/activity-request.ts
  components/location-select-drawer.tsx
  components/multi-file-upload.tsx
Labels: feature, fix

#115 등록한 활동 수정 폼 구현
  app/(protected)/(user)/dashboard/my-activity/_components/activity-edit-form.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/location-select-section.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/my-activity-card.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/my-activity-kebab.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/my-activity-list.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/schedule-section.tsx
  components/location-select-drawer.tsx
Labels: feature

#117 질문 페이지 분리
  app/(protected)/(detail)/activity/[activityId]/_components/author-info.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/detail-carousel.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/detail-content.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/detail-description.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/detail-title.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/kakao-map.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/promise-request-form.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/share-popover.tsx
  app/(protected)/(detail)/activity/[activityId]/page.tsx
  app/(protected)/(detail)/layout.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-list.tsx
  app/(protected)/(detail)/question/[questionId]/_components/question-detail.tsx
  app/(protected)/(detail)/question/[questionId]/page.tsx
  app/(protected)/(main)/activity-list/_components/activity-list-card.tsx
  app/(protected)/(main)/activity-list/_components/sorting-dropdown.tsx
  app/(protected)/(main)/question-list/_components/answer-edit-form.tsx
  app/(protected)/(main)/question-list/_components/answer-form.tsx
  app/(protected)/(main)/question-list/_components/question-detail-modal.tsx
  app/(protected)/(main)/question-list/_components/question-form.tsx
  app/(protected)/(main)/question-list/_components/question-list-card.tsx
  app/(protected)/(main)/question-list/_components/question-list.tsx
  app/(protected)/(main)/question-list/_components/question-sort-dropdown.tsx
  app/(protected)/(main)/question-list/_components/qusetion-tip-popover.tsx
  app/(protected)/(main)/question-list/page.tsx
  app/data/activity-request.ts
  app/data/question.ts
  constants/sort.ts
Labels: fix, refactor

#118 네비게이션 바 구현 및 레이아웃 수정
  app/(protected)/(detail)/layout.tsx
  app/(protected)/(main)/_components/location-combobox.tsx
  app/(protected)/(main)/_components/nav-with-combobox.tsx
  app/(protected)/(main)/_components/nav-with-route.tsx
  app/(protected)/(main)/activity-list/_components/sorting-dropdown.tsx
  app/(protected)/(main)/layout.tsx
  app/(protected)/(user)/dashboard/_components/dashboard-nav.tsx
  app/(protected)/(user)/dashboard/_components/nav-icon-link.tsx
  app/(protected)/(user)/dashboard/_components/plus-button.tsx
  app/(protected)/(user)/dashboard/layout.tsx
  app/(protected)/(user)/dashboard/my-activity/page.tsx
  app/(protected)/(user)/layout.tsx
  app/(protected)/_components/nav-base.tsx
  app/(protected)/_components/nav-dropdown.tsx
  components/common/nav-base.tsx
  components/common/nav-dropdown.tsx
  components/common/nav-footer.tsx
  components/location-command.tsx
  components/location-select-drawer-nav.tsx
  constants/nav-routes.ts
  hooks/useLocationSelect.ts
Labels: fix, refactor

#119 삭제 알림 모달 연결
  app/(protected)/(user)/dashboard/my-activity/_components/my-activity-kebab.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-kebab.tsx
  components/delete-alert-modal.tsx
Labels: refactor

#120 메인페이지 로딩 구현
  app/(protected)/(main)/_components/main-carousel.tsx
  app/(protected)/(main)/_components/profile-dropdown.tsx
  app/(protected)/(main)/activity-list/_components/activity-container.tsx
  app/(protected)/(main)/activity-list/_components/activity-list-card.tsx
  app/(protected)/(main)/activity-list/_components/activity-list.tsx
  app/(protected)/(main)/activity-list/_components/sorting-dropdown.tsx
  app/(protected)/(main)/activity-list/loading.tsx
  app/(protected)/(main)/activity-list/page.tsx
  app/data/activity.ts
  components/common/back-button.tsx
  components/skeletons/activity-card-skeleton.tsx
  components/skeletons/carousel-card-skeleton.tsx
  components/ui/skeleton.tsx
Labels: feature, fix, refactor

#122 캐러셀 디자인 수정
  app/(protected)/(detail)/activity/[activityId]/_components/detail-carousel.tsx
  app/(protected)/(main)/_components/carousel-card.tsx
  app/(protected)/(main)/_components/carousel-text.tsx
  components/dot-indicator.tsx
Labels: style

#123 대시보드 나의 활동 개선
  app/(protected)/(user)/dashboard/layout.tsx
  app/(protected)/(user)/dashboard/loading.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/activity-create-form.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/activity-create-modal.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/activity-edit-form.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/detail-info-section.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/location-select-section.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/my-activity-card.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/my-activity-list.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/schedule-section.tsx
  app/(protected)/(user)/dashboard/my-activity/create/page.tsx
  app/(protected)/(user)/dashboard/my-activity/page.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-create-modal.tsx
  app/(protected)/(user)/layout.tsx
  components/common/nav-footer.tsx
  components/common/plus-button.tsx
  components/image-card.tsx
  components/location-select-drawer.tsx
  components/multi-file-upload.tsx
  components/skeletons/my-activity-card-skeleton.tsx
Labels: feature, fix, style, refactor

#124 질문 상세 페이지 수정
  app/(protected)/(detail)/layout.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-button-container.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-delete-modal.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-edit-form.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-form.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-item.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-kebab.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-list.tsx
  app/(protected)/(detail)/question/[questionId]/_components/question-detail.tsx
  app/(protected)/(detail)/question/[questionId]/page.tsx
  app/(protected)/(main)/question-list/_components/question-detail-modal.tsx
  components/common/close-button.tsx
  components/ui/separator.tsx
  package.json
Labels: fix, style, refactor

#125 캐러셀 수정
  app/(protected)/(detail)/activity/[activityId]/_components/author-info.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/detail-carousel.tsx
  app/(protected)/(main)/_components/carousel-card.tsx
  app/(public)/introduction/[introductionId]/_components/profile-rank.tsx
  components/profile-item.tsx
  public/default-carousel-image.png
Labels: style

#126 대시보드 개선
  app/(protected)/(main)/activity-list/_components/activity-list.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/my-activity-card.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/my-activity-list.tsx
  app/(protected)/(user)/dashboard/promise-list/_components/promise-list-card.tsx
  app/(protected)/(user)/dashboard/promise-list/_components/promise-list.tsx
  app/(protected)/(user)/dashboard/promise-list/_components/promise-status.tsx
  app/(protected)/(user)/dashboard/promise-list/page.tsx
  app/(protected)/(user)/dashboard/promised-list/_components/promised-list-card.tsx
  app/(protected)/(user)/dashboard/promised-list/_components/promised-list.tsx
  app/(protected)/(user)/dashboard/promised-list/page.tsx
  app/(protected)/(user)/dashboard/wishlist/_components/wishlist-container.tsx
  app/(protected)/(user)/dashboard/wishlist/_components/wishlist-heart-icon.tsx
  app/(protected)/(user)/dashboard/wishlist/page.tsx
  app/(protected)/(user)/layout.tsx
  app/action/activity.ts
  components/common/nav-dropdown.tsx
  components/delete-alert-modal.tsx
  components/image-card.tsx
  components/small-button.tsx
  constants/nav-routes.ts
Labels: refactor

#127 질문 폼 수정, 대시보드 내 질문 페이지 수정
  app/(protected)/(detail)/activity/[activityId]/_components/share-popover.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-kebab.tsx
  app/(protected)/(main)/question-list/_components/question-form.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-card.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-edit-form.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-kebab.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-list.tsx
  app/(protected)/(user)/dashboard/my-question/page.tsx
  app/(protected)/(user)/dashboard/wishlist/_components/wishlist-container.tsx
  components/image-card.tsx
  components/location-select-drawer.tsx
Labels: fix, refactor

#129 프로젝트 전체적으로 개선
  app/(protected)/(detail)/question/[questionId]/_components/answer-edit-form.tsx
  app/(protected)/(main)/_components/carousel-card.tsx
  app/(protected)/(main)/activity-list/_components/activity-container.tsx
  app/(protected)/(main)/activity-list/page.tsx
  app/(protected)/(main)/question-list/_components/question-form.tsx
  app/(protected)/(main)/question-list/_components/question-list-card.tsx
  app/(protected)/(main)/question-list/_components/question-list.tsx
  app/(protected)/(main)/question-list/_components/question-sort-dropdown.tsx
  app/(protected)/(main)/question-list/page.tsx
  app/(protected)/(user)/dashboard/promise-list/_components/promise-list.tsx
  app/(protected)/(user)/dashboard/reviews/_components/rating-selector.tsx
  app/(protected)/(user)/dashboard/reviews/_components/review-list.tsx
  app/(protected)/(user)/dashboard/reviews/_components/review-mock.ts
  app/(protected)/(user)/dashboard/reviews/_components/reviews-card.tsx
  app/(protected)/(user)/dashboard/reviews/page.tsx
  app/(protected)/(user)/profile/_components/profile-topic.tsx
  app/(protected)/(user)/profile/edit/_components/edit-image-form.tsx
  app/(protected)/(user)/profile/edit/_components/edit-profile-item.tsx
  app/(protected)/(user)/profile/edit/page.tsx
  app/(protected)/(user)/profile/layout.tsx
  app/(protected)/(user)/profile/page.tsx
  app/(public)/introduction/[introductionId]/page.tsx
  components/common/nav-base.tsx
  components/dot-indicator.tsx
  components/location-select-drawer-nav.tsx
  components/profile-item.tsx
  components/skeletons/carousel-card-skeleton.tsx
  components/sorting-dropdown.tsx
  components/upload-button.tsx
  constants/nav-routes.ts
  constants/ratings.ts
  constants/sort.ts
  package-lock.json
Labels: refactor

#132 질문관련 버그 해결 및 스타일 수정
  app/(protected)/(detail)/activity/[activityId]/_components/detail-title.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/share-popover.tsx
  app/(protected)/(detail)/layout.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-edit-form.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-item.tsx
  app/(protected)/(detail)/question/[questionId]/_components/question-detail.tsx
  app/(protected)/(main)/question-list/_components/question-detail-modal.tsx
  app/(protected)/(main)/question-list/_components/question-list-card.tsx
  app/(protected)/(main)/question-list/page.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-create-modal.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-form.tsx
  app/(protected)/(user)/dashboard/my-question/page.tsx
  app/data/question.ts
  components/common/plus-button.tsx
  components/sorting-dropdown.tsx
  type.ts
Labels: fix

#134 레이아웃 이슈 외 적용
  app/(protected)/(main)/_components/carousel-text.tsx
  app/(protected)/(main)/activity-list/loading.tsx
  app/(protected)/(main)/activity-list/page.tsx
  app/(protected)/(main)/layout.tsx
  app/(protected)/(main)/question-list/_components/question-list-card.tsx
  app/(protected)/(main)/question-list/page.tsx
  app/(protected)/(user)/dashboard/layout.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/activity-create-form.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/activity-edit-form.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/detail-info-section.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/my-activity-list.tsx
  app/(protected)/(user)/dashboard/my-activity/create/page.tsx
  app/(protected)/(user)/dashboard/my-activity/page.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-create-modal.tsx
  app/(protected)/(user)/dashboard/my-question/page.tsx
  app/(protected)/(user)/dashboard/promise-list/_components/promise-list.tsx
  app/(protected)/(user)/dashboard/promise-list/page.tsx
  app/(protected)/(user)/dashboard/promised-list/_components/promised-list.tsx
  app/(protected)/(user)/dashboard/promised-list/page.tsx
  app/(protected)/(user)/dashboard/reviews/_components/review-list.tsx
  app/(protected)/(user)/dashboard/reviews/page.tsx
  app/(protected)/(user)/dashboard/wishlist/_components/wishlist-container.tsx
  app/(protected)/(user)/dashboard/wishlist/page.tsx
  app/(protected)/(user)/layout.tsx
  app/(protected)/(user)/profile/layout.tsx
  components/common/nav-footer.tsx
  components/common/plus-div.tsx
  components/location-select-drawer-nav.tsx
  components/multi-file-upload.tsx
  components/sorting-dropdown.tsx
  tailwind.config.ts
Labels: refactor

#135 메인페이지 스타일링
  app/(protected)/(main)/activity-list/_components/activity-list-card.tsx
  app/(public)/_components/landing-hero-section.tsx
  app/(public)/_components/landing-main-section.tsx
  public/ActivityPage.png
  public/LandingBackground.jpg
  public/QuestionPage.png
Labels: fix, style

#136 메인 이미지 디폴트 적용 및 버튼 텍스트 색상 변경
  app/(protected)/(detail)/activity/[activityId]/_components/promise-request-form.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-button-container.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-edit-form.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-form.tsx
  app/(protected)/(main)/activity-list/_components/activity-list-card.tsx
  app/(protected)/(main)/question-list/_components/question-list-card.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-card.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-create-modal.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-edit-form.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-form.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-list.tsx
  app/(protected)/(user)/dashboard/my-question/page.tsx
  app/(protected)/(user)/profile/edit/_components/edit-image-form.tsx
  app/(protected)/(user)/profile/edit/_components/edit-nickname-form.tsx
  app/(protected)/(user)/profile/edit/_components/edit-password-form.tsx
  app/(protected)/topic/_components/tag-footer.tsx
  app/(public)/introduction/[introductionId]/_components/back-button 2.tsx
Labels: fix, refactor

#138 프로필 개선
  app/(protected)/(user)/profile/_components/profile-image.tsx
  app/(protected)/(user)/profile/edit/_components/edit-image-form.tsx
  app/(protected)/(user)/profile/edit/_components/edit-item-nickname.tsx
  app/(protected)/(user)/profile/edit/_components/edit-item-password.tsx
  app/(protected)/(user)/profile/edit/_components/edit-nickname-form.tsx
  app/(protected)/(user)/profile/edit/_components/edit-profile-item.tsx
  app/(protected)/(user)/profile/edit/_components/edit-profile-topic.tsx
  app/(protected)/(user)/profile/edit/_components/render-avatar.tsx
  app/(protected)/(user)/profile/edit/page.tsx
  app/(protected)/(user)/profile/layout.tsx
  components/profile-item.tsx
Labels: refactor

#139 랜딩 넓이 수정
  app/(auth)/layout.tsx
  app/(public)/_components/landing-hero-section.tsx
  app/(public)/_components/landing-main-section.tsx
  app/(public)/page.tsx
Labels: refactor

#141 fix: 신청카드 긴급 수정
  app/(protected)/(user)/dashboard/promise-list/_components/promise-list-card.tsx
  app/(protected)/(user)/dashboard/promise-list/_components/promise-list.tsx
  components/image-card.tsx
Labels: fix

#145 serachparam으로 드롭다운 텍스트 설정
  components/sorting-dropdown.tsx
Labels: fix, refactor

#146 drawer 로직 수정
  components/location-select-drawer-nav.tsx
Labels: fix, refactor

#147 activity-list페이지 생성 버튼 추가
  app/(protected)/(main)/activity-list/page.tsx
Labels: feature

#149 import 변경
  app/(protected)/(main)/activity-list/page.tsx
Labels: fix

#160 위치기반 서비스
  app/(protected)/(main)/activity-list/_components/activity-carousel.tsx
  app/(protected)/(main)/activity-list/_components/activity-list-card.tsx
  app/(protected)/(main)/activity-list/_components/activity-list.tsx
  app/(protected)/(main)/question-list/_components/question-location-popover.tsx
  app/data/activity.ts
  components/location-select-drawer-nav.tsx
  components/location-select-drawer.tsx
  constants/locations.ts
  utils/calculateDistance.ts
Labels: feature

#163 스타일 수정
  app/(auth)/layout.tsx
  app/(auth)/sign-in/page.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/detail-carousel.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/kakao-map.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/promise-request-form.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/share-popover.tsx
  app/(protected)/(detail)/activity/[activityId]/page.tsx
  app/(protected)/(detail)/layout.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-kebab.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-list.tsx
  app/(protected)/(main)/_components/profile-dropdown.tsx
  app/(protected)/(main)/activity-list/loading.tsx
  app/(protected)/(main)/activity-list/page.tsx
  app/(protected)/(main)/layout.tsx
  app/(protected)/(main)/question-list/page.tsx
  app/(protected)/(user)/dashboard/layout.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/my-activity-card.tsx
  app/(protected)/(user)/dashboard/my-activity/create/page.tsx
  app/(protected)/(user)/dashboard/my-activity/page.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-kebab.tsx
  app/(protected)/(user)/dashboard/my-question/page.tsx
  app/(protected)/(user)/dashboard/promise-list/_components/promise-list.tsx
  app/(protected)/(user)/dashboard/promise-list/page.tsx
  app/(protected)/(user)/dashboard/promised-list/_components/promised-list.tsx
  app/(protected)/(user)/dashboard/promised-list/page.tsx
  app/(protected)/(user)/dashboard/reviews/_components/review-list.tsx
  app/(protected)/(user)/dashboard/reviews/page.tsx
  app/(protected)/(user)/dashboard/wishlist/_components/wishlist-container.tsx
  app/(protected)/(user)/dashboard/wishlist/page.tsx
  app/(protected)/(user)/profile/edit/page.tsx
  app/(protected)/(user)/profile/layout.tsx
  app/(protected)/(user)/profile/page.tsx
  app/(protected)/topic/page.tsx
  app/(public)/_components/landing-main-section.tsx
  app/(public)/introduction/[introductionId]/_components/back-button 2.tsx
  app/(public)/introduction/[introductionId]/page.tsx
  app/(public)/introduction/rank-test/page 2.tsx
  app/(public)/page.tsx
  app/_components/gila-layout.tsx
  app/layout.tsx
  components/common/nav-base.tsx
  components/common/nav-dropdown.tsx
  components/common/nav-footer.tsx
  components/delete-alert-modal.tsx
  components/location-select-drawer-nav.tsx
  components/location-select-drawer.tsx
  components/sorting-dropdown.tsx
  components/ui/alert-dialog.tsx
  components/ui/calendar.tsx
  components/ui/dialog.tsx
  components/ui/drawer.tsx
  components/ui/sonner.tsx
  tailwind.config.ts
Labels: fix, style

#173 style: 반응형 스타일링 적용
  app/(auth)/layout.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/detail-content.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/promise-request-form.tsx
  app/(protected)/(main)/activity-list/_components/activity-container.tsx
  app/(protected)/(main)/activity-list/loading.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/my-activity-list.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-create-modal.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-list.tsx
  app/(protected)/(user)/dashboard/promise-list/_components/promise-list.tsx
  app/(protected)/(user)/dashboard/promised-list/_components/promised-list.tsx
  app/(protected)/(user)/dashboard/promised-list/page.tsx
  app/(protected)/(user)/dashboard/reviews/_components/review-list.tsx
  app/(protected)/(user)/dashboard/reviews/page.tsx
  app/(protected)/(user)/dashboard/wishlist/_components/wishlist-container.tsx
  app/(protected)/(user)/profile/edit/page.tsx
  app/(protected)/(user)/profile/layout.tsx
  app/(protected)/(user)/profile/page.tsx
  app/(protected)/topic/page.tsx
  app/(public)/_components/landing-nav.tsx
  app/(public)/introduction/[introductionId]/page.tsx
  app/layout.tsx
  components/common/nav-base.tsx
  components/common/nav-footer.tsx
  components/small-button.tsx
Labels: style

#175 fix: 중복으로 활동 로드 수정 및 위치 기반 서비스 수정
  app/(protected)/(main)/activity-list/_components/activity-carousel.tsx
  app/(protected)/(main)/activity-list/_components/activity-container.tsx
  app/(protected)/(main)/activity-list/_components/activity-list.tsx
  app/(protected)/(main)/activity-list/page.tsx
Labels: fix, refactor

#176 Develop
  app/(protected)/(main)/activity-list/_components/activity-carousel.tsx
  app/(protected)/(main)/activity-list/_components/activity-container.tsx
  app/(protected)/(main)/activity-list/_components/activity-list.tsx
  app/(protected)/(main)/activity-list/page.tsx
Labels: fix, refactor

#177 fix: 위치기반 서비스 로직 수정, 지역 명 수정
  app/(protected)/(main)/activity-list/_components/activity-carousel.tsx
  app/(protected)/(main)/activity-list/_components/activity-list.tsx
  app/(protected)/(user)/profile/edit/page.tsx
  app/(protected)/(user)/profile/page.tsx
  constants/locations.ts
Labels: fix, refactor

#180 fix: 날짜 지난활동 스타일 및 기능 구현 및 근처 추천 리스트 위치 수정
  app/(protected)/(detail)/activity/[activityId]/_components/promise-request-form.tsx
  app/(protected)/(main)/activity-list/_components/activity-list-card.tsx
  app/(protected)/(main)/activity-list/_components/activity-list.tsx
  app/(protected)/(main)/activity-list/_components/activity-slide-container.tsx
  app/(protected)/(main)/activity-list/_components/activity-slide.tsx
Labels: fix, refactor

#183 슬라이드 버튼 구현
  app/(protected)/(main)/activity-list/_components/activity-slide.tsx
  app/(protected)/(main)/activity-list/_components/slide-button-container.tsx
  app/(protected)/(main)/activity-list/_components/slide-button.tsx
  hooks/useThrottle.ts
Labels: feature

#186 로케이션 기반 리스트 로직 수정, 대시보드 스타일링
  app/(protected)/(main)/activity-list/_components/activity-list.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/my-activity-list.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-list.tsx
  app/(protected)/(user)/dashboard/promise-list/_components/promise-list.tsx
  app/(protected)/(user)/dashboard/promised-list/_components/promised-list.tsx
  app/(protected)/(user)/dashboard/reviews/_components/review-list.tsx
  app/(protected)/(user)/dashboard/wishlist/_components/wishlist-container.tsx
  app/data/activity.ts
  public/GrayLogo.svg
  public/test.png
Labels: fix

#189 닉네임 중복 방지 기능 구현
  app/action/user.ts
  app/data/user.ts
  prisma/schema.prisma
Labels: feature

#190 채팅기능 구현
  app/(protected)/(user)/dashboard/my-chat/_components/channel.tsx
  app/(protected)/(user)/dashboard/my-chat/_components/chat-channel-list.tsx
  app/(protected)/(user)/dashboard/my-chat/page.tsx
  app/(protected)/chat/[[...channel]]/_components/chat-page.tsx
  app/(protected)/chat/[[...channel]]/_components/chat.tsx
  app/(protected)/chat/[[...channel]]/_components/message-card.tsx
  app/(protected)/chat/[[...channel]]/_components/message-input.tsx
  app/(protected)/chat/[[...channel]]/_components/message-list.tsx
  app/(protected)/chat/[[...channel]]/page.tsx
  app/(protected)/chat/layout.tsx
  app/data/user.ts
  constants/nav-routes.ts
  package-lock.json
  package.json
Labels: feature

#194 fix: 슬라이드 2개부터 버튼 생성
  app/(protected)/(main)/activity-list/_components/activity-slide.tsx
Labels: fix

#193 채팅관련 대시보드 카드 기능 추가 및 스타일 수정
  app/(protected)/(user)/dashboard/my-chat/_components/channel.tsx
  app/(protected)/(user)/dashboard/promise-list/_components/promise-list-card.tsx
Labels: feature, fix, style

#195 fix: 전체적인 스타일 수정
  app/(protected)/(user)/dashboard/my-chat/_components/channel.tsx
  app/(protected)/(user)/dashboard/promise-list/page.tsx
  app/(protected)/(user)/dashboard/wishlist/_components/wishlist-image-card.tsx
  app/(protected)/chat/[[...channel]]/_components/chat.tsx
  app/(protected)/chat/[[...channel]]/_components/message-card.tsx
  app/(protected)/chat/[[...channel]]/page.tsx
  app/(protected)/chat/layout.tsx
Labels: fix, style

#197 endDate 지난 활동 처리
  app/(protected)/(main)/activity-list/_components/activity-slide.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/my-activity-card.tsx
  app/(protected)/(user)/dashboard/my-activity/page.tsx
  app/(protected)/(user)/dashboard/my-chat/page.tsx
  app/(protected)/(user)/dashboard/my-question/page.tsx
  app/(protected)/(user)/dashboard/promise-list/_components/promise-list.tsx
  app/(protected)/(user)/dashboard/promise-list/page.tsx
  app/(protected)/(user)/dashboard/promised-list/page.tsx
  app/(protected)/(user)/dashboard/reviews/page.tsx
  app/(protected)/(user)/dashboard/wishlist/page.tsx
  app/data/activity-request.ts
  app/data/activity.ts
  app/data/chat.ts
Labels: fix, refactor

#199 사이드 메뉴 구현
  app/(protected)/(detail)/activity/[activityId]/_components/detail-carousel.tsx
  app/(protected)/chat/[[...channel]]/_components/message-input.tsx
  components/common/nav-base.tsx
  components/common/nav-sidemenu.tsx
  components/ui/sheet.tsx
  package-lock.json
  tailwind.config.ts
Labels: feature, fix

#202 온라인 유저 상태 리스트로 구현
  app/(protected)/chat/[[...channel]]/_components/chat-online-list.tsx
  app/(protected)/chat/[[...channel]]/_components/chat-online-user.tsx
  app/(protected)/chat/[[...channel]]/_components/chat-page.tsx
  app/(protected)/chat/[[...channel]]/_components/chat.tsx
  app/(protected)/chat/[[...channel]]/page.tsx
Labels: feature

#204 Fix chat
  app/(protected)/chat/[[...channel]]/_components/chat-page.tsx
  app/(protected)/chat/[[...channel]]/_components/chat.tsx
  app/(protected)/chat/[[...channel]]/_components/message-input.tsx
Labels: fix, style

#207 폴더 구조 변경 및 스타일 추가
  app/(protected)/chat/[channel]/_components/chat-online-list.tsx
  app/(protected)/chat/[channel]/_components/chat-online-user.tsx
  app/(protected)/chat/[channel]/_components/chat-page.tsx
  app/(protected)/chat/[channel]/_components/chat.tsx
  app/(protected)/chat/[channel]/_components/message-card.tsx
  app/(protected)/chat/[channel]/_components/message-input.tsx
  app/(protected)/chat/[channel]/_components/message-list.tsx
  app/(protected)/chat/[channel]/page.tsx
Labels: refactor
