Repository Gila-part4/Gila, pull requests merged in 2024-07, with the labels that each got.

#10 캐러셀 구현
  components/ui/card.tsx
  components/ui/carousel-card.tsx
  components/ui/carousel-text.tsx
  components/ui/carousel.tsx
  components/ui/main-carousel.tsx
  package-lock.json
  package.json
Labels: feature

#12 카드 마크업
  app/(protected)/(main)/activity-list/_components/activity-list-card.tsx
  app/(protected)/(main)/activity-list/page.tsx
  app/(protected)/(main)/question-list/_components/question-list-card.tsx
  app/(protected)/(main)/question-list/page.tsx
  app/(protected)/(main)/test-list/page.tsx
  app/(protected)/(user)/dashboard/my-activity/page.tsx
  app/(protected)/(user)/dashboard/my-question/page.tsx
  app/(protected)/(user)/dashboard/promise-list/page.tsx
  app/(protected)/(user)/dashboard/promised-list/page.tsx
  app/(protected)/(user)/dashboard/reviews/page.tsx
  app/(protected)/(user)/dashboard/wishlist/page.tsx
  app/(protected)/(user)/profile/page.tsx
  app/(protected)/[activityId]/page.tsx
  app/(protected)/topic/page.tsx
  app/(public)/(main)/page.tsx
  app/(public)/introduction/page.tsx
  app/(public)/page.tsx
  app/globals.css
  public/test.png
Labels: feature

#21 메인 페이지 조립 및 파일 경로 수정
  app/(auth)/sign-up/_components/register-form.tsx
  app/(protected)/(main)/_components/carousel-card.tsx
  app/(protected)/(main)/_components/carousel-text.tsx
  app/(protected)/(main)/_components/location-combobox.tsx
  app/(protected)/(main)/_components/main-carousel.tsx
  app/(protected)/(main)/_components/nav-with-combobox.tsx
  app/(protected)/(main)/activity-list/_components/activity-list-card.tsx
  app/(protected)/(main)/activity-list/_components/activity-list.tsx
  app/(protected)/(main)/activity-list/page.tsx
  app/(protected)/(main)/layout.tsx
  app/(protected)/(main)/question-list/_components/question-list-card.tsx
  app/(public)/(main)/page.tsx
  app/action/activity-request.ts
  app/action/activity.ts
  app/action/answer.ts
  app/action/favorite.ts
  app/action/question.ts
  app/action/review.ts
  app/action/user.ts
  app/data/activity-request.ts
  app/data/activity.ts
  app/data/answer.ts
  app/data/favorite.ts
  app/data/question.ts
  app/data/review.ts
  app/data/user.ts
  components/logout-button.tsx
  components/ui/card.tsx
  components/ui/carousel.tsx
  components/ui/combobox.tsx
  components/ui/command.tsx
  components/ui/dialog.tsx
  components/ui/popover.tsx
  constants/locations.ts
  lib/db.ts
  lib/utils.ts
  package-lock.json
  package.json
  prisma/schema.prisma
  public/test.png
  schema.ts
  type.ts
Labels: feature, fix

#20 auth페이지(로그인, 회원가입)수정
  app/(auth)/sign-in/_components/login-form.tsx
  app/(auth)/sign-in/page.tsx
  app/(auth)/sign-up/_components/register-form.tsx
  app/(auth)/sign-up/page.tsx
  components/ui/password-input.tsx
  middleware.ts
  routes.ts
Labels: fix

#16 물어보기 질문 생성 폼 구현
  app/(protected)/(main)/question-list/_components/question-form.tsx
  app/(protected)/(main)/question-list/page.tsx
  components/ui/textarea.tsx
Labels: feature

#32 상세 페이지
  app/(protected)/[activityId]/_components/author-info.tsx
  app/(protected)/[activityId]/_components/detail-carousel.tsx
  app/(protected)/[activityId]/_components/detail-content.tsx
  app/(protected)/[activityId]/_components/detail-description.tsx
  app/(protected)/[activityId]/_components/detail-title.tsx
  app/(protected)/[activityId]/_components/kakao-map.tsx
  app/(protected)/[activityId]/_components/promise-request-form.tsx
  app/(protected)/[activityId]/page.tsx
  components/ui/avatar.tsx
  package-lock.json
  package.json
  public/kakaomap.png
  public/map.png
Labels: feature

#27 랜딩 페이지 로그인 버튼 수정
  app/(public)/(main)/page.tsx
  app/(public)/page.tsx
Labels: fix, style

#31 메인페이지 작업
  app/(protected)/(main)/_components/location-combobox.tsx
  app/(protected)/(main)/_components/nav-with-combobox.tsx
  app/(protected)/(main)/_components/nav-with-route.tsx
  app/(protected)/(main)/layout.tsx
  components/ui/command.tsx
  components/ui/dropdown-menu.tsx
  package-lock.json
  package.json
Labels: feature, style

#18 답변 모달
  app/(protected)/(main)/question-list/_components/answer-form.tsx
  app/(protected)/(main)/question-list/_components/answer-item.tsx
  app/(protected)/(main)/question-list/_components/answer-list.tsx
  app/(protected)/(main)/question-list/_components/question-detail-modal.tsx
  components/ui/dialog.tsx
  components/ui/textarea.tsx
Labels: feature

#28 인증 페이지 레이아웃 및 로고 추가
  app/(auth)/layout.tsx
  app/(auth)/sign-in/_components/login-form.tsx
  app/(auth)/sign-in/page.tsx
  app/(auth)/sign-up/_components/register-form.tsx
  app/(auth)/sign-up/page.tsx
  components/ui/password-input.tsx
  constants/regex.ts
  schema.ts
Labels: feature, fix, style

#22 action, get sample code 구현 완료
  app/(test)/layout.tsx
  app/(test)/test-action/activity/[activityId]/_components/create-sample-activity-request-button.tsx
  app/(test)/test-action/activity/[activityId]/_components/create-sample-review-button.tsx
  app/(test)/test-action/activity/[activityId]/page.tsx
  app/(test)/test-action/activity/_components/create-sample-activity-button.tsx
  app/(test)/test-action/activity/_components/favorite-button.tsx
  app/(test)/test-action/activity/page.tsx
  app/(test)/test-action/page.tsx
  app/(test)/test-action/profile/page.tsx
  app/(test)/test-action/question/[questionId]/_components/create-sample-answer-button.tsx
  app/(test)/test-action/question/[questionId]/page.tsx
  app/(test)/test-action/question/_components/create-sample-question-button.tsx
  app/(test)/test-action/question/page.tsx
  app/action/activity-request.ts
  app/action/activity.ts
  app/action/answer.ts
  app/action/favorite.ts
  app/action/question.ts
  app/action/review.ts
  app/data/activity-request.ts
  app/data/activity.ts
  app/data/answer.ts
  app/data/favorite.ts
  app/data/question.ts
  app/data/review.ts
  app/data/user.ts
  middleware.ts
  package.json
  prisma/schema.prisma
  type.ts
Labels: feature

#30 대시보드 리스트, 카드 구현
  app/(protected)/(user)/dashboard/_components/plus-button.tsx
  app/(protected)/(user)/dashboard/layout.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/my-activity-card.tsx
  app/(protected)/(user)/dashboard/my-activity/page.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-card.tsx
  app/(protected)/(user)/dashboard/my-question/page.tsx
  app/(protected)/(user)/dashboard/promise-list/_components/promise-list-card.tsx
  app/(protected)/(user)/dashboard/promise-list/_components/promise-status.tsx
  app/(protected)/(user)/dashboard/promise-list/page.tsx
  app/(protected)/(user)/dashboard/promised-list/_components/promised-list-card.tsx
  app/(protected)/(user)/dashboard/promised-list/page.tsx
  app/(protected)/(user)/dashboard/reviews/_components/rating-selector.tsx
  app/(protected)/(user)/dashboard/reviews/_components/reviews-card.tsx
  app/(protected)/(user)/dashboard/reviews/page.tsx
  app/(protected)/(user)/dashboard/wishlist/_components/wishlist-card.tsx
  app/(protected)/(user)/dashboard/wishlist/page.tsx
  components/dropdown-kebab.tsx
  components/image-card.tsx
  components/small-button.tsx
  components/user-icon.tsx
Labels: feature, style
