Repository Gila-part4/Gila, pull requests merged in 2024-09, with the labels that each got.

#209 footer 메뉴 버튼 사이드 메뉴로 변경
  app/(protected)/(main)/activity-list/_components/activity-slide-container.tsx
  app/(protected)/(user)/dashboard/layout.tsx
  app/(protected)/(user)/profile/layout.tsx
  components/common/nav-sidemenu.tsx
  components/common/sidemenu-accordion.tsx
  constants/nav-routes.ts
Labels: feature, fix

#210 사이드메뉴로 변경으로 발생한 스타일 오류 수정
  app/(protected)/(detail)/layout.tsx
  app/(protected)/(main)/activity-list/_components/activity-container.tsx
  app/(protected)/(main)/layout.tsx
  app/(protected)/(user)/dashboard/layout.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/my-activity-list.tsx
  app/(protected)/(user)/dashboard/my-activity/page.tsx
  app/(protected)/(user)/dashboard/my-chat/_components/chat-channel-list.tsx
  app/(protected)/(user)/dashboard/my-chat/page.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-create-modal.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-list.tsx
  app/(protected)/(user)/dashboard/my-question/page.tsx
  app/(protected)/(user)/dashboard/promise-list/_components/promise-list.tsx
  app/(protected)/(user)/dashboard/promise-list/page.tsx
  app/(protected)/(user)/dashboard/promised-list/_components/promised-list.tsx
  app/(protected)/(user)/dashboard/promised-list/page.tsx
  app/(protected)/(user)/dashboard/reviews/_components/review-list.tsx
  app/(protected)/(user)/dashboard/reviews/page.tsx
  app/(protected)/(user)/dashboard/wishlist/_components/wishlist-container.tsx
  app/(protected)/(user)/dashboard/wishlist/page.tsx
  app/(protected)/(user)/profile/edit/page.tsx
  app/(protected)/(user)/profile/layout.tsx
  app/(protected)/(user)/profile/page.tsx
  components/common/close-button.tsx
  components/common/nav-dropdown.tsx
Labels: fix, style

#215 fix: 대시보드 리스트 버그 수정
  app/data/activity-request.ts
Labels: bug

#212 이메일 인증 로직 구현
  app/(auth)/layout.tsx
  app/(auth)/sign-up/_components/register-form.tsx
  app/(auth)/sign-up/page.tsx
  app/action/mail.ts
  package-lock.json
  package.json
  schema.ts
Labels: feature

#217 약속 요청, 약속 응답 메일 발송
  app/(auth)/sign-up/_components/register-form.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/promise-request-form.tsx
  app/(protected)/(detail)/activity/[activityId]/page.tsx
  app/(protected)/(user)/dashboard/my-chat/_components/chat-channel-list.tsx
  app/(protected)/(user)/dashboard/promised-list/_components/promised-list-card.tsx
  app/action/mail.ts
  app/data/chat.ts
Labels: feature

#222 date-fns 위치 수정
  package-lock.json
  package.json
  utils/formatDateRange.tsx
Labels: bug, refactor

#224 요청 상태 표시, revalidate 수정
  app/(protected)/(detail)/activity/[activityId]/_components/promise-request-form.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/activity-edit-form.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/my-activity-card.tsx
  app/action/activity.ts
  app/action/answer.ts
  app/action/favorite.ts
  app/action/question.ts
  app/action/review.ts
  app/data/activity-request.ts
Labels: feature, fix

#226 채팅 권한 구현
  app/(protected)/(user)/dashboard/my-chat/_components/channel.tsx
  app/(protected)/(user)/dashboard/my-chat/_components/chat-channel-list.tsx
  app/(protected)/(user)/dashboard/my-chat/page.tsx
  app/(protected)/chat/[channel]/_components/chat-online-list.tsx
  app/(protected)/chat/[channel]/_components/chat-online-user.tsx
  app/(protected)/chat/[channel]/_components/chat-page.tsx
  app/(protected)/chat/[channel]/_components/chat.tsx
  app/(protected)/chat/[channel]/page.tsx
  app/data/chat.ts
  type.ts
Labels: feature

#228 질문 리스트 페이지 수정
  app/(protected)/(main)/question-list/_components/question-list.tsx
  app/(protected)/(main)/question-list/page.tsx
  app/data/activity.ts
  app/data/question.ts
  components/location-select-drawer-nav.tsx
Labels: refactor

#232 대시보드 내 질문 카드 변경
  app/(protected)/(user)/dashboard/my-question/_components/my-question-card.tsx
  app/(protected)/(user)/dashboard/my-question/page.tsx
  components/skeletons/question-card-skeleton.tsx
  components/ui/card.tsx
Labels: fix, style

#216 Primary색상 CTA 버튼 구현
  app/(auth)/sign-in/_components/login-form.tsx
  app/(auth)/sign-up/_components/register-form.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/promise-request-form.tsx
  app/(protected)/(main)/question-list/_components/question-form.tsx
  components/common/primary-CTA-button.tsx
  components/location-select-drawer-nav.tsx
  components/location-select-drawer.tsx
Labels: feature

#233 suspense 제거, 질문 리스트 스켈레톤 추가
  app/(protected)/(main)/activity-list/loading.tsx
  app/(protected)/(main)/activity-list/page.tsx
  app/(protected)/(main)/question-list/_components/question-list.tsx
  app/(protected)/(user)/dashboard/my-activity/page.tsx
  app/(protected)/(user)/dashboard/my-chat/page.tsx
  app/(protected)/(user)/dashboard/my-question/page.tsx
  app/(protected)/(user)/dashboard/promise-list/page.tsx
  app/(protected)/(user)/dashboard/promised-list/page.tsx
  app/(protected)/(user)/dashboard/reviews/page.tsx
  app/(protected)/(user)/dashboard/wishlist/page.tsx
Labels: refactor

#237 채팅 멤버 수정, import 수정, 프로필 페이지 스타일 수정
  app/(protected)/(detail)/question/[questionId]/_components/answer-kebab.tsx
  app/(protected)/(main)/question-list/_components/question-location-popover.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/my-activity-card.tsx
  app/(protected)/(user)/dashboard/my-chat/_components/channel.tsx
  app/(protected)/(user)/dashboard/my-chat/_components/chat-channel-list.tsx
  app/(protected)/(user)/dashboard/my-chat/page.tsx
  app/(protected)/(user)/profile/page.tsx
  app/(protected)/chat/[channel]/_components/chat-online-list.tsx
  app/(protected)/chat/[channel]/_components/chat-page.tsx
  app/(protected)/chat/[channel]/_components/chat.tsx
  app/(protected)/chat/[channel]/_components/message-list.tsx
  app/(protected)/chat/[channel]/page.tsx
  app/action/mail.ts
  app/action/user.ts
  app/data/question.ts
  components/common/nav-base.tsx
  components/common/nav-sidemenu.tsx
  components/profile-item.tsx
  components/skeletons/my-activity-card-skeleton.tsx
  components/ui/combobox.tsx
  components/ui/dropdown-menu.tsx
  components/ui/popover.tsx
Labels: style, refactor

#241 위치 기반 기능 react-query 적용
  app/(protected)/(main)/activity-list/_components/activity-slide-container.tsx
  app/(protected)/(main)/activity-list/_components/activity-slide.tsx
  app/(protected)/(main)/activity-list/page.tsx
  app/layout.tsx
  app/utils/providers.tsx
  package-lock.json
  package.json
Labels: fix, refactor

#245 fix: auth.js 세션에 유저 이름 추가
  auth.ts
Labels: refactor

#243 활동, 질문, 대시보드 리스트 suspense적용
  app/(protected)/(main)/activity-list/_components/activity-container.tsx
  app/(protected)/(main)/activity-list/_components/activity-list-skeleton.tsx
  app/(protected)/(main)/activity-list/page.tsx
  app/(protected)/(main)/question-list/_components/question-container.tsx
  app/(protected)/(main)/question-list/_components/question-list-skeleton.tsx
  app/(protected)/(main)/question-list/page.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/my-activity-container.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/my-activity-skeleton.tsx
  app/(protected)/(user)/dashboard/my-activity/page.tsx
  app/(protected)/(user)/dashboard/my-chat/_components/chat-container.tsx
  app/(protected)/(user)/dashboard/my-chat/page.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-container.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-skeleton.tsx
  app/(protected)/(user)/dashboard/my-question/page.tsx
  app/(protected)/(user)/dashboard/promise-list/_components/promise-container.tsx
  app/(protected)/(user)/dashboard/promise-list/page.tsx
  app/(protected)/(user)/dashboard/promised-list/_components/promised-container.tsx
  app/(protected)/(user)/dashboard/promised-list/_components/promised-skeleton.tsx
  app/(protected)/(user)/dashboard/promised-list/page.tsx
  app/(protected)/(user)/dashboard/reviews/_components/review-container.tsx
  app/(protected)/(user)/dashboard/reviews/_components/review-skeleton.tsx
  app/(protected)/(user)/dashboard/reviews/page.tsx
  app/(protected)/(user)/dashboard/wishlist/_components/wishList-skeleton.tsx
  app/(protected)/(user)/dashboard/wishlist/_components/wishlist-container.tsx
  app/(protected)/(user)/dashboard/wishlist/_components/wishlist.tsx
  app/(protected)/(user)/dashboard/wishlist/page.tsx
Labels: fix, refactor

#246 fix: 유저 이름 auth.js 세션 활용
  app/(protected)/(user)/dashboard/my-activity/page.tsx
  app/(protected)/(user)/dashboard/my-chat/page.tsx
  app/(protected)/(user)/dashboard/my-question/page.tsx
  app/(protected)/(user)/dashboard/promise-list/page.tsx
  app/(protected)/(user)/dashboard/promised-list/page.tsx
  app/(protected)/(user)/dashboard/wishlist/page.tsx
  app/(protected)/(user)/profile/edit/page.tsx
  components/common/nav-base.tsx
  components/common/nav-sidemenu.tsx
Labels: refactor

#251 회원가입 form 로직 수정 및 폼 스키마 분리
  app/(auth)/sign-in/_components/login-form.tsx
  app/(auth)/sign-up/_components/register-form.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-edit-form.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-form.tsx
  app/(protected)/(main)/question-list/_components/question-form.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-edit-form.tsx
  app/(protected)/(user)/dashboard/my-question/_components/my-question-form.tsx
  components/ui/password-input.tsx
  constants/form-schema.ts
Labels: refactor

#255 상세페이지 스켈레톤
  app/(protected)/(detail)/activity/[activityId]/_components/activity-detail-sksleton.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/detail-content.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/request-container.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/request-skeleton.tsx
  app/(protected)/(detail)/activity/[activityId]/page.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-form.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-list-container.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-list-skeleton.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-list.tsx
  app/(protected)/(detail)/question/[questionId]/_components/question-detail-skeleton.tsx
  app/(protected)/(detail)/question/[questionId]/_components/question-detail.tsx
  app/(protected)/(detail)/question/[questionId]/page.tsx
  app/(protected)/(main)/question-list/_components/question-list-skeleton.tsx
  components/skeletons/answer-card-skeleton.tsx
Labels: style, refactor

#260 Fix card style
  app/(protected)/(main)/activity-list/_components/activity-list-card.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/activity-create-form.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/activity-edit-form.tsx
  app/(protected)/(user)/dashboard/my-activity/_components/my-activity-card.tsx
  app/(protected)/(user)/dashboard/my-chat/_components/channel.tsx
  app/(protected)/(user)/dashboard/promise-list/_components/promise-list-card.tsx
  app/(protected)/(user)/dashboard/promised-list/_components/promised-list-card.tsx
  app/(protected)/(user)/dashboard/reviews/_components/reviews-card.tsx
  app/(protected)/(user)/dashboard/wishlist/_components/wishlist-image-card.tsx
  components/common/plus-div.tsx
  components/delete-alert-modal.tsx
  components/image-card.tsx
  components/location-select-drawer.tsx
  components/small-button.tsx
  components/sorting-dropdown.tsx
  components/ui/button.tsx
  constants/form-schema.ts
Labels: style, refactor

#261 auth session 로직 수정
  app/(protected)/(detail)/activity/[activityId]/_components/promise-request-form.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/request-container.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-list-container.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-list.tsx
  app/(protected)/(user)/dashboard/my-activity/page.tsx
  app/(protected)/(user)/dashboard/my-chat/page.tsx
  app/(protected)/(user)/dashboard/my-question/page.tsx
  app/(protected)/(user)/dashboard/promise-list/page.tsx
  app/(protected)/(user)/dashboard/promised-list/page.tsx
  app/(protected)/(user)/dashboard/wishlist/page.tsx
  app/(protected)/(user)/profile/edit/page.tsx
  app/(protected)/(user)/profile/page.tsx
  app/action/activity-request.ts
  app/action/activity.ts
  app/action/answer.ts
  app/action/favorite.ts
  app/action/mail.ts
  app/action/question.ts
  app/action/review.ts
  app/action/user.ts
  app/api/uploadthing/core.ts
  app/data/activity-request.ts
  app/data/activity.ts
  app/data/chat.ts
  app/data/favorite.ts
  app/data/question.ts
  app/data/user.ts
  components/common/nav-base.tsx
Labels: fix, refactor

#263 프로필 관련 페이지 suspense 및 스켈레톤 적용
  app/(protected)/(user)/profile/_components/profile-container.tsx
  app/(protected)/(user)/profile/_components/profile-skeleton.tsx
  app/(protected)/(user)/profile/edit/_components/edit-profile-container.tsx
  app/(protected)/(user)/profile/edit/page.tsx
  app/(protected)/(user)/profile/page.tsx
  app/(public)/introduction/[introductionId]/_components/introduce-container.tsx
  app/(public)/introduction/[introductionId]/layout.tsx
  app/(public)/introduction/[introductionId]/page.tsx
Labels: style, refactor

#266 비로그인 유저 기능 적용
  app/(protected)/(detail)/activity/[activityId]/_components/detail-content.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/detail-title.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/promise-request-form.tsx
  app/(protected)/(detail)/activity/[activityId]/_components/request-container.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-list-container.tsx
  app/(protected)/(detail)/question/[questionId]/_components/answer-list.tsx
  app/(protected)/(detail)/question/[questionId]/page.tsx
  app/(protected)/(main)/question-list/page.tsx
  app/(protected)/(user)/dashboard/my-activity/page.tsx
  app/(protected)/(user)/dashboard/my-chat/page.tsx
  app/(protected)/(user)/dashboard/my-question/page.tsx
  app/(protected)/(user)/dashboard/promise-list/page.tsx
  app/(protected)/(user)/dashboard/promised-list/page.tsx
  app/(protected)/(user)/dashboard/wishlist/page.tsx
  app/(protected)/(user)/profile/edit/page.tsx
  app/(protected)/(user)/profile/page.tsx
  app/(protected)/chat/[channel]/page.tsx
  app/(public)/_components/landing-hero-section.tsx
  app/action/activity-request.ts
  app/action/activity.ts
  app/action/answer.ts
  app/action/favorite.ts
  app/action/mail.ts
  app/action/question.ts
  app/action/review.ts
  app/action/user.ts
  app/api/uploadthing/core.ts
  app/data/activity-request.ts
  app/data/activity.ts
  app/data/chat.ts
  app/data/favorite.ts
  app/data/question.ts
  app/data/user.ts
  components/common/nav-base.tsx
  components/common/nav-sidemenu.tsx
  components/loginLink-area.tsx
  middleware.ts
  utils/toastLoginMessage.ts
Labels: fix, refactor

#268 fix: revalidate 적용
  app/action/activity-request.ts
  app/action/activity.ts
Labels: fix
